#!/usr/bin/perl

use warnings;
use strict;

use feature 'say';

use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/../lib" }

use TransmissionIdentifierBase;

use Data::Dumper;

my $base = TransmissionIdentifierBase->new();

say "base: " . Dumper($base);

$base->audio_to_spectrogram(
    { input => './samples/461.205_1533495682.wav',
      output => '/tmp/461.205_1533495682.wav.png',
    }
                  )

#say $transid->net_astext;

#my $detect = $transid->is_voice(
#    #'training/test/voice/461.080_1533496176.wav.png'
#     'training/test/data/461.205_1533495707.wav.png'
#    );

